//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.Supplier_WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Supplier_WebService.IWsServiceCatalog")]
    public interface IWsServiceCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getAllServices", ReplyAction="http://tempuri.org/IWsServiceCatalog/getAllServicesResponse")]
        string getAllServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getAllServices", ReplyAction="http://tempuri.org/IWsServiceCatalog/getAllServicesResponse")]
        System.Threading.Tasks.Task<string> getAllServicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getServiceNames", ReplyAction="http://tempuri.org/IWsServiceCatalog/getServiceNamesResponse")]
        string getServiceNames();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getServiceNames", ReplyAction="http://tempuri.org/IWsServiceCatalog/getServiceNamesResponse")]
        System.Threading.Tasks.Task<string> getServiceNamesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getServiceID", ReplyAction="http://tempuri.org/IWsServiceCatalog/getServiceIDResponse")]
        string getServiceID(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getServiceID", ReplyAction="http://tempuri.org/IWsServiceCatalog/getServiceIDResponse")]
        System.Threading.Tasks.Task<string> getServiceIDAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsServiceCatalogChannel : Company.Supplier_WebService.IWsServiceCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsServiceCatalogClient : System.ServiceModel.ClientBase<Company.Supplier_WebService.IWsServiceCatalog>, Company.Supplier_WebService.IWsServiceCatalog {
        
        public WsServiceCatalogClient() {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getAllServices() {
            return base.Channel.getAllServices();
        }
        
        public System.Threading.Tasks.Task<string> getAllServicesAsync() {
            return base.Channel.getAllServicesAsync();
        }
        
        public string getServiceNames() {
            return base.Channel.getServiceNames();
        }
        
        public System.Threading.Tasks.Task<string> getServiceNamesAsync() {
            return base.Channel.getServiceNamesAsync();
        }
        
        public string getServiceID(string name) {
            return base.Channel.getServiceID(name);
        }
        
        public System.Threading.Tasks.Task<string> getServiceIDAsync(string name) {
            return base.Channel.getServiceIDAsync(name);
        }
    }
}
