//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.SvcRefVendor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Service", Namespace="http://schemas.datacontract.org/2004/07/Supplier_1.DAL")]
    [System.SerializableAttribute()]
    public partial class Service : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime gsDatetimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gsImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal gsPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gsQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gsStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gssIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gssLongDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gssNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string gssShortDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gssTypeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int gsvendorIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime gsDatetime {
            get {
                return this.gsDatetimeField;
            }
            set {
                if ((this.gsDatetimeField.Equals(value) != true)) {
                    this.gsDatetimeField = value;
                    this.RaisePropertyChanged("gsDatetime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gsImage {
            get {
                return this.gsImageField;
            }
            set {
                if ((object.ReferenceEquals(this.gsImageField, value) != true)) {
                    this.gsImageField = value;
                    this.RaisePropertyChanged("gsImage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal gsPrice {
            get {
                return this.gsPriceField;
            }
            set {
                if ((this.gsPriceField.Equals(value) != true)) {
                    this.gsPriceField = value;
                    this.RaisePropertyChanged("gsPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gsQuantity {
            get {
                return this.gsQuantityField;
            }
            set {
                if ((this.gsQuantityField.Equals(value) != true)) {
                    this.gsQuantityField = value;
                    this.RaisePropertyChanged("gsQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gsStatus {
            get {
                return this.gsStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.gsStatusField, value) != true)) {
                    this.gsStatusField = value;
                    this.RaisePropertyChanged("gsStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gssID {
            get {
                return this.gssIDField;
            }
            set {
                if ((object.ReferenceEquals(this.gssIDField, value) != true)) {
                    this.gssIDField = value;
                    this.RaisePropertyChanged("gssID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gssLongDesc {
            get {
                return this.gssLongDescField;
            }
            set {
                if ((object.ReferenceEquals(this.gssLongDescField, value) != true)) {
                    this.gssLongDescField = value;
                    this.RaisePropertyChanged("gssLongDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gssName {
            get {
                return this.gssNameField;
            }
            set {
                if ((object.ReferenceEquals(this.gssNameField, value) != true)) {
                    this.gssNameField = value;
                    this.RaisePropertyChanged("gssName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string gssShortDesc {
            get {
                return this.gssShortDescField;
            }
            set {
                if ((object.ReferenceEquals(this.gssShortDescField, value) != true)) {
                    this.gssShortDescField = value;
                    this.RaisePropertyChanged("gssShortDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gssTypeID {
            get {
                return this.gssTypeIDField;
            }
            set {
                if ((this.gssTypeIDField.Equals(value) != true)) {
                    this.gssTypeIDField = value;
                    this.RaisePropertyChanged("gssTypeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gsvendorID {
            get {
                return this.gsvendorIDField;
            }
            set {
                if ((this.gsvendorIDField.Equals(value) != true)) {
                    this.gsvendorIDField = value;
                    this.RaisePropertyChanged("gsvendorID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SvcRefVendor.IWsServiceCatalog")]
    public interface IWsServiceCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/GetServices", ReplyAction="http://tempuri.org/IWsServiceCatalog/GetServicesResponse")]
        Company.SvcRefVendor.Service[] GetServices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/GetServices", ReplyAction="http://tempuri.org/IWsServiceCatalog/GetServicesResponse")]
        System.Threading.Tasks.Task<Company.SvcRefVendor.Service[]> GetServicesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsServiceCatalogChannel : Company.SvcRefVendor.IWsServiceCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsServiceCatalogClient : System.ServiceModel.ClientBase<Company.SvcRefVendor.IWsServiceCatalog>, Company.SvcRefVendor.IWsServiceCatalog {
        
        public WsServiceCatalogClient() {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Company.SvcRefVendor.Service[] GetServices() {
            return base.Channel.GetServices();
        }
        
        public System.Threading.Tasks.Task<Company.SvcRefVendor.Service[]> GetServicesAsync() {
            return base.Channel.GetServicesAsync();
        }
    }
}
