//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IWsServiceCatalog2")]
    public interface IWsServiceCatalog2 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog2/getAllService2", ReplyAction="http://tempuri.org/IWsServiceCatalog2/getAllService2Response")]
        System.Data.DataSet getAllService2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog2/getAllService2", ReplyAction="http://tempuri.org/IWsServiceCatalog2/getAllService2Response")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllService2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsServiceCatalog2Channel : Company.ServiceReference2.IWsServiceCatalog2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsServiceCatalog2Client : System.ServiceModel.ClientBase<Company.ServiceReference2.IWsServiceCatalog2>, Company.ServiceReference2.IWsServiceCatalog2 {
        
        public WsServiceCatalog2Client() {
        }
        
        public WsServiceCatalog2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsServiceCatalog2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalog2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalog2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getAllService2() {
            return base.Channel.getAllService2();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllService2Async() {
            return base.Channel.getAllService2Async();
        }
    }
}
