//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IWsServiceCatalog")]
    public interface IWsServiceCatalog {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getAllService", ReplyAction="http://tempuri.org/IWsServiceCatalog/getAllServiceResponse")]
        System.Data.DataSet getAllService();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/getAllService", ReplyAction="http://tempuri.org/IWsServiceCatalog/getAllServiceResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> getAllServiceAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDate", ReplyAction="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDateResponse")]
        System.Data.DataSet SelectInvoiceDate();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDate", ReplyAction="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDateResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectInvoiceDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDetails", ReplyAction="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDetailsResponse")]
        System.Data.DataSet SelectInvoiceDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDetails", ReplyAction="http://tempuri.org/IWsServiceCatalog/SelectInvoiceDetailsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> SelectInvoiceDetailsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWsServiceCatalogChannel : Company.ServiceReference1.IWsServiceCatalog, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsServiceCatalogClient : System.ServiceModel.ClientBase<Company.ServiceReference1.IWsServiceCatalog>, Company.ServiceReference1.IWsServiceCatalog {
        
        public WsServiceCatalogClient() {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalogClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsServiceCatalogClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getAllService() {
            return base.Channel.getAllService();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getAllServiceAsync() {
            return base.Channel.getAllServiceAsync();
        }
        
        public System.Data.DataSet SelectInvoiceDate() {
            return base.Channel.SelectInvoiceDate();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectInvoiceDateAsync() {
            return base.Channel.SelectInvoiceDateAsync();
        }
        
        public System.Data.DataSet SelectInvoiceDetails() {
            return base.Channel.SelectInvoiceDetails();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> SelectInvoiceDetailsAsync() {
            return base.Channel.SelectInvoiceDetailsAsync();
        }
    }
}
